=== syllant/idea-plugin-revu/main/resources/org/sylfra/idea/plugins/revu/resources/schemas/revu_1_0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xs="http://plugins.intellij.net/revu"
            targetNamespace="http://plugins.intellij.net/revu"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.1">

  <xsd:element name="review">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:history"/>
        <xsd:element ref="xs:goal" minOccurs="0"/>
        <xsd:element ref="xs:referential"/>
        <xsd:element ref="xs:issues" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="status" type="xsd:string" use="required"/>
      <xsd:attribute name="shared" type="xsd:boolean" use="required"/>
      <xsd:attribute name="extends" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="referential">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:priorities"/>
        <xsd:element ref="xs:tags" minOccurs="0"/>
        <xsd:element ref="xs:users" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="priorities">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:priority" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tags">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:tag" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="users">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:user" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="priority">
    <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="order" type="xsd:byte" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tag">
    <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="user">
    <xsd:complexType>
      <xsd:attribute name="displayName" type="xsd:string" use="required"/>
      <xsd:attribute name="login" type="xsd:string" use="required"/>
      <xsd:attribute name="password" type="xsd:string" use="optional"/>
      <xsd:attribute name="roles" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="history">
    <xsd:complexType>
      <xsd:attribute name="createdBy" type="xsd:string" use="required"/>
      <xsd:attribute name="lastUpdatedBy" type="xsd:string" use="required"/>
      <xsd:attribute name="createdOn" type="xsd:dateTime" use="required"/>
      <xsd:attribute name="lastUpdatedOn" type="xsd:dateTime" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="goal">
    <xsd:complexType mixed="true" />
  </xsd:element>

  <xsd:element name="issues">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:issue" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="issue">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:history"/>
        <xsd:element ref="xs:desc" minOccurs="0"/>
        <xsd:element ref="xs:notes" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attribute name="summary" type="xsd:string" use="required"/>
      <xsd:attribute name="filePath" type="xsd:string" use="required"/>
      <xsd:attribute name="vcsRev" type="xsd:string" use="optional"/>
      <xsd:attribute name="localRev" type="xsd:string" use="optional"/>
      <xsd:attribute name="lineStart" type="xsd:int" use="optional"/>
      <xsd:attribute name="lineEnd" type="xsd:int" use="optional"/>
      <xsd:attribute name="hash" type="xsd:string" use="required"/>
      <xsd:attribute name="tags" type="xsd:string" use="optional"/>
      <xsd:attribute name="priority" type="xsd:string" use="required"/>
      <xsd:attribute name="status" type="xs:status" use="required"/>
      <xsd:attribute name="recipients" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="status">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="to_resolve"/>
      <xsd:enumeration value="resolved"/>
      <xsd:enumeration value="reopened"/>
      <xsd:enumeration value="closed"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="desc">
    <xsd:complexType mixed="true" />
  </xsd:element>

  <xsd:element name="notes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:note" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="note">
    <xsd:complexType mixed="true">
      <xsd:attribute name="createdBy" type="xsd:string" use="required"/>
      <xsd:attribute name="createdOn" type="xsd:dateTime" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== syllant/idea-plugin-revu/src/test/resources/review-test-unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<review xmlns="http://plugins.intellij.net/revu"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://plugins.intellij.net/revu http://plugins.intellij.net/revu/ns/revu_1_0.xsd"
        name="Test review" status="draft" shared="true">
  <history createdBy="u1" lastUpdatedBy="u2" createdOn="2008-01-01T12:00:00" lastUpdatedOn="2008-01-01T12:00:00"/>
  <goal>A test review. A test review. A test review. A test review. A test review.</goal>
  <referential>
    <priorities>
      <priority order="1" name="priority1"/>
      <priority order="2" name="priority2"/>
      <priority order="3" name="priority3"/>
    </priorities>
    <tags>
      <tag name="tag1"/>
      <tag name="tag2"/>
    </tags>
    <users>
      <user displayName="user1" login="u1" password="p1" roles="admin"/>
      <user displayName="user2" login="u2" password="p2" roles="admin,reviewer"/>
      <user displayName="user3" login="u3" password="p3" roles="reviewer,author"/>
    </users>
  </referential>
  <issues>
    <issue summary="Test item review 1" filePath="Test-1.java" lineStart="1" lineEnd="2" hash="1" tags="tag1"
          priority="priority1" status="to_resolve">
      <history createdBy="u2" lastUpdatedBy="u3" createdOn="2008-01-01T12:00:00" lastUpdatedOn="2008-02-02T12:00:00"/>
      <desc>Test item review 1. Test item review 1.</desc>
    </issue>
    <issue summary="Test item review 2" filePath="Test-2.java" lineStart="2" lineEnd="5" hash="1" tags="tag2"
          priority="priority2" status="to_resolve">
      <history createdBy="u3" lastUpdatedBy="u1" createdOn="2008-02-01T12:00:00" lastUpdatedOn="2008-03-02T12:00:00"/>
      <desc>Test item review 2. Test item review 2.</desc>
    </issue>
  </issues>
</review>

=== syllant/idea-plugin-revu/main/resources/org/sylfra/idea/plugins/revu/resources/defaultReviewTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<review xmlns="http://plugins.intellij.net/revu"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://plugins.intellij.net/revu http://plugins.intellij.net/xstructure/ns/revu_1_0.xsd"
        name="[Default]" status="_template" shared="true">
  <history createdBy="[default]" lastUpdatedBy="[default]" createdOn="2008-01-01T00:00:00" lastUpdatedOn="2008-01-01T00:00:00"/>
  <goal><![CDATA[Default review provided as a template to extends / copy.

You may use this template when you don't want customize tags or priorities defined by default.

Otherwise, you should create another template suiting your needs]]></goal>
  <referential>
    <priorities>
      <priority order="0" name="low"/>
      <priority order="1" name="normal"/>
      <priority order="2" name="high"/>
    </priorities>
    <tags>
      <tag name="tag1"/>
      <tag name="tag2"/>
    </tags>
  </referential>
</review>
